sudo: required

services:
  - docker

before_install:
  - docker build -t hardikjoshi2110/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hardikjoshi2110/react-test npm test

after_success:
  - docker build -t hardikjoshi2110/multi-client ./client
  - docker build -t hardikjoshi2110/multi-nginx ./nginx
  - docker build -t hardikjoshi2110/multi-server ./server
  - docker build -t hardikjoshi2110/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to docker hub
  - docker push hardikjoshi2110/multi-client
  - docker push hardikjoshi2110/multi-nginx
  - docker push hardikjoshi2110/multi-server
  - docker push hardikjoshi2110/multi-worker
